apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/rook-ceph
  - ../base/rook-ceph-cluster
patchesStrategicMerge:
  - rook-ceph-values.yaml
  - rook-ceph-cluster-values.yaml
