apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ceph/dev
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-0
      namespace: rook-ceph
  prune: true
  wait: false
  timeout: 5m0s
