apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    grafana:
      adminUser: admin
      adminPassword: password
