apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx-stable/nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
