apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cni
spec:
  releaseName: cni
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
      version: "1.0.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cni-values
