apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: rook
spec:
  releaseName: rook
  chart:
    spec:
      chart: rook
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v1.7.2
