apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      version: ">=0.0.1"
  values:
    image:
      tag: v1.7.2
    csi:
      provisionerTolerations:
        - key: storage-node
          operator: Exists
          effect: NoSchedule
      pluginTolerations:
        - key: storage-node
          operator: Exists
          effect: NoSchedule
